server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${application.spring.datasource.url}
    username: ${application.spring.datasource.username}
    password: ${application.spring.datasource.password}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    gcp:
      storage:
        credentials:
          location: ${application.spring.cloud.gcp.storage.credentials.location}
        project-id: ${application.spring.cloud.gcp.storage.project-id}
        bucket: ${application.spring.cloud.gcp.storage.bucket}

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${spring.security.oauth2.client.registration.google.client-id}
            client-secret: ${spring.security.oauth2.client.registration.google.client-secret}
            redirect-uri: http://localhost:8080/auth/redirect/google
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Google
            scope:
              - profile
              - email

  data:
    redis:
      port: ${spring.data.redis.port}
      host: ${spring.data.redis.host}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  api:
    url: ${application.spring.api.url}
    key: ${application.spring.api.key}

logging:
  level:
    com.drugbox.common: debug

jwt:
  secret: ${application.jwt.secret}
  secret_refresh: ${application.jwt.secret_refresh}